---
- name: Configure Pi Zero camera server
  hosts: pi_cameras
  gather_facts: no
  become: true

  vars:
    mediamtx_version: v1.16.3
    install_dir: /home/zero/mediamtx-install

  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install nala
    apt:
      name: nala
      state: present

  - name: Run nala fetch
    command: nala fetch --auto -y

  - name: Set WIFI Power save config
    template:
      src: templates/wifi-powersave.conf
      dest: /etc/NetworkManager/conf.d/wifi-powersave.conf
      mode: '0644'

  - name: Set running WIFI Power save 
    command:
      cmd: iw dev wlan0 set power_save off

  - name: Update system packages
    command: nala update

  - name: Install camera packages
    apt:
      name: rpicam-apps
      state: present

  - name: Enable camera interface
    command: raspi-config nonint do_camera 0


  # -----------------------------
  # Check if mediamtx exists
  # -----------------------------

  - name: Check if mediamtx binary exists
    stat:
      path: /usr/local/bin/mediamtx
    register: mediamtx_binary


  # -----------------------------
  # Install mediamtx if missing
  # -----------------------------

  - name: Install mediamtx
    block:

      - name: Create install directory
        file:
          path: "{{ install_dir }}"
          state: directory
          owner: {{ansible_user}}
          group: {{ansible_user}}

      - name: Download mediamtx tarball
        get_url:
          url: "https://github.com/bluenviron/mediamtx/releases/download/{{ mediamtx_version }}/mediamtx_{{ mediamtx_version }}_linux_arm64.tar.gz"
          dest: "{{ install_dir }}/mediamtx.tar.gz"

      - name: Extract mediamtx
        command:
          cmd: tar -xvf mediamtx.tar.gz
          chdir: "{{ install_dir }}"

      - name: Move mediamtx binary to system path
        command:
          cmd: mv mediamtx /usr/local/bin/
          chdir: "{{ install_dir }}"

    when: not mediamtx_binary.stat.exists


  # -----------------------------
  # Deploy configuration
  # -----------------------------

  - name: Copy MediaMTX config
    copy:
      src: files/mediamtx.yml
      dest: /home/zero/mediamtx.yml
      owner: {{ansible_user}}
      group: {{ansible_user}}
      mode: '0644'


  # -----------------------------
  # Install systemd service
  # -----------------------------

  - name: Install systemd service
    template:
      src: templates/pi-zero-cam-streaming.service.j2
      dest: /etc/systemd/system/pi-zero-cam-streaming.service
      mode: '0644'


  - name: Reload systemd
    systemd:
      daemon_reload: yes


  - name: Enable and start streaming service
    systemd:
      name: pi-zero-cam-streaming.service
      enabled: yes
      state: started