---
- name: Configure Pi Zero camera server
  hosts: pi_cameras
  gather_facts: no
  become: true

  vars:
    mediamtx_version: v1.16.3
    install_dir: /home/zero/mediamtx-install

  tasks:


  # -----------------------------
  # Check if mediamtx exists
  # -----------------------------

  - name: Check if mediamtx binary exists
    stat:
      path: /usr/local/bin/mediamtx
    register: mediamtx_binary


  # -----------------------------
  # Install mediamtx if missing
  # -----------------------------

  - name: Install mediamtx
    block:

      - name: Create install directory
        file:
          path: "{{ install_dir }}"
          state: directory
          owner: "{{ansible_user}}"
          group: "{{ansible_user}}"

      - name: Download mediamtx tarball
        get_url:
          url: "https://github.com/bluenviron/mediamtx/releases/download/{{ mediamtx_version }}/mediamtx_{{ mediamtx_version }}_linux_arm64.tar.gz"
          dest: "{{ install_dir }}/mediamtx.tar.gz"

      - name: Extract mediamtx
        command:
          cmd: tar -xvf mediamtx.tar.gz
          chdir: "{{ install_dir }}"

      - name: Move mediamtx binary to system path
        command:
          cmd: mv mediamtx /usr/local/bin/
          chdir: "{{ install_dir }}"

    when: not mediamtx_binary.stat.exists


  # -----------------------------
  # Deploy configuration
  # -----------------------------

  - name: Copy MediaMTX config
    copy:
      src: files/mediamtx.yml
      dest: /home/zero/mediamtx.yml
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: '0644'

  - name: Copy MediaMTX day config
    copy:
      src: files/mediamtx_day.yml
      dest: /home/zero/mediamtx_day.yml
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: '0644'

  - name: Copy MediaMTX night config
    copy:
      src: files/mediamtx_night.yml
      dest: /home/zero/mediamtx_night.yml
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: '0644'

  - name: Schedule day camera profile
    ansible.builtin.cron:
      name: "Day profile"
      minute: "00"
      hour: "5"
      user: "{{ansible_user}}"
      job: "cp -f ~/mediamtx_day.yml ~/mediamtx.yml"

  - name: Schedule night camera profile
    ansible.builtin.cron:
      name: "Night profile"
      minute: "00"
      hour: "19"
      user: "{{ansible_user}}"
      job: "cp -f ~/mediamtx_night.yml ~/mediamtx.yml"


  # -----------------------------
  # Install systemd service
  # -----------------------------

  - name: Install systemd service
    template:
      src: templates/pi-zero-cam-streaming.service.j2
      dest: /etc/systemd/system/pi-zero-cam-streaming.service
      mode: '0644'


  - name: Reload systemd
    systemd:
      daemon_reload: yes


  - name: Enable and start streaming service
    systemd:
      name: pi-zero-cam-streaming.service
      enabled: yes
      state: started